on: [push, pull_request]

name: CI Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the changes from Git
        uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          version: '10'
      - name: Install dependencies
        run: npm ci
      - name: Execute tests
        run: npm test
      - name: Record code coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
